project:
  type: website
  output-dir: docs
website:
  title: "Subhrajyoty Roy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: research/index.qmd
        text: Research
      - href: software.qmd
        text: OSS
      - href: research/talks.qmd
        text: Talks
      - href: notes/index.qmd
        text: Notes
    search: true
    tools:
      - icon: github
        href: https://github.com/subroy13
      - icon: linkedin
        href: https://www.linkedin.com/in/subroy13
      - icon: envelope-at
        href: mailto:roy.s@wustl.edu
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=Gocm0lYAAAAJ&hl=en&authuser=1
  page-footer: 
    center: Â© 2025 Subhrajyoty Roy
  back-to-top-navigation: true
  # cookie-consent: true

format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: ./static/css/styles.css
    smooth-scroll: true


